version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=testDB
      - DB_USER=postgres
      - DB_PASSWORD=codingdnn8

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: codingdnn8
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
